version: '2'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - net-redis
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes

  register-center:
    build:
      context: ./register-center
    restart: always
    networks:
      - net-register-center
    ports:
      - 8088:8088
    container_name: register-center
    image: register-center
    cap_add:
      - ALL

  producer:
    build:
      context: ./producer
    restart: always
    networks:
      - net-register-center
    ports:
      - 8081:8081
    container_name: producer
    image: producer
    depends_on:
      - register-center
    cap_add:
      - ALL

  consumer:
    build:
      context: ./consumer
    restart: always
    networks:
      - net-register-center
      - net-redis
      - net-producer
    ports:
      - 8082:8082
    container_name: consumer
    image: consumer
#    volumes:
#      - "/home/test/consumer:/home"
    depends_on:
      - register-center
      - producer
      - redis
    cap_add:
      - ALL

networks:
  net-redis:
    driver: bridge
  net-register-center:
    driver: bridge
  net-producer:
    driver: bridge