version: '2'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - net-redis
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes --protected-mode no --bind 0.0.0.0

  register-center:
    build:
      context: ./register-center
    container_name: register-center
    image: register-center
    restart: always
    networks:
      - net-register-center
    ports:
      - 8088:8088
    cap_add:
      - ALL

  producer:
    build:
      context: ./producer
    container_name: producer
    image: producer
    restart: always
    networks:
      - net-producer
      - net-register-center
    ports:
      - 8081:8081
    depends_on:
      - register-center
    cap_add:
      - ALL

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    image: consumer
    restart: always
    networks:
      - net-redis
      - net-register-center
      - net-producer
    ports:
      - 8082:8082
    volumes:
      - "/data/logs:/data/logs"
    depends_on:
      - register-center
      - producer
      - redis
    cap_add:
      - ALL

networks:
  net-redis:
    driver: bridge
  net-register-center:
    driver: bridge
  net-producer:
    driver: bridge