version: '2'
services:
  register-center:
    build:
      context: ./register-center
    restart: always
    ports:
      - 8088:8088
    container_name: register-center
    hostname: register-center-host
    image: register-center

  producer:
    build:
      context: ./producer
    restart: always
    ports:
      - 8081:8081
    container_name: producer
    hostname: producer-host
    image: producer

  consumer:
    build:
      context: ./consumer
    restart: always
    ports:
      - 8082:8082
    container_name: consumer
    hostname: consumer-host
    image: consumer