
server:
  port: 8082
# 注册中心地址
register.center: http://net-register-center:8088/register

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: consumer
  # 默认自动注入的redis配置
  redis:
    password: 123456
# 多redisTemplate实例配置, 根据名称注入
# 默认配置 hostName: localhost; password: none; port: 6379; database: 0
multi-redis:
  redisConfigs:
    redisTemplate0:
#      hostName: localhost
      password: 123456
      port: 6379
      database: 0
    redisTemplate1:
      hostName: localhost
      password: 123456
      port: 6379
      database: 1
    redisTemplate2:
      hostName: localhost
      password: 123456
      port: 6379
      database: 2