
server:
  port: 8082
# 注册中心地址
regist.center: localhost:8088/regist

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: consumer

# 多redisTemplate实例配置
multi-redis:
  redisTemplateConfigs:
    redisNode0:
      hostName: localhost
      password: 123456
      port: 6379
      database: 0
    redisNode1:
      hostName: localhost
      password: 123456
      port: 6379
      database: 1
    redisNode2:
      hostName: localhost
      password: 123456
      port: 6379
      database: 2